### ISSUE TITLE
testing the plugin 

### ISSUE THREAD

**Issue by 3C0D** [mnaoumov/obsidian-root-folder-context-menu#2]

**Comment by 3C0D** [comment]
I did an update of the config to be sure to have a good configuration but the error is still there. 
I noticed in an update you did that you are using target: ESNEXT that's not the best because you can have some incompatibilities with obsidian electron...
there this is the kind of error I have linked to obsidian-typings
![image](https://github.com/user-attachments/assets/bf1d6f42-bb47-44de-a845-19ee3931d17f)

**Comment by 3C0D** [comment]
this is not the exact place for this discussion, but I wanted to talk with you about it before to report directly on obsidian-typings because it was linked to my tests on your plugin.

**Comment by mnaoumov** [comment]
@3C0D you've been using `InternalPluginName` incorrectly.

[README](https://github.com/Fevol/obsidian-typings?tab=readme-ov-file#obsidian-typingsimplementations) had an explicit example of the usage.

Current repo was confusing because it used an old version of `obsidian-typings` that didn't require the new syntax.

I updated this repo to the latest version of `obsidian-typings` and use proper syntax. See https://github.com/mnaoumov/obsidian-root-folder-context-menu/blob/af8af5a2b8707cf8a135ee5e9afe2c8a96c47d96/src/RootFolderContextMenuPlugin.ts#L15

**Comment by 3C0D** [comment]
Oh, I deleted my comment because I thought it might be embarrassing. It’s really nice to have found a solution. I’m studying your obsidian-dev-utils repo, and it’s incredibly complex to me. I need to understand things more than just using them. Of course, I will keep trying. Now I’m lucky because I can ask a lot of questions to AIs. But even so, it’s still super hard, and my memory feels like a giant hole, so I take notes on everything. But that’s fine; five years ago, I hadn’t written a single line of code, and I was over 45 years old. I’m interested in what I’m experiencing through this journey, regardless of any limitations. It’s reassuring to see that others are much stronger in their skills, and it’s very relevant to realize that "reality" is the same, no matter the level of skill achieved.

**Comment by 3C0D** [comment]
ok now the config is ok. I simplified a little the code readability around the around...
in your code there is a little mistake on the condition file.isRoot() it's file.isRoot
https://github.com/3C0D/context-menu-test

**Comment by 3C0D** [comment]
it's a nice hack the click to close the menu. I put it after opening the menu but like it's faster it's doing it well without timeout. I will this in some of my plugins...
